INSTA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/follow/', views.follow, name='follow'),
    
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('index2/', views.index2, name='index2'),
    path('index3/', views.index3, name='index3'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:post_id>/comments/<int:id>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:post_id>/comments/<int:id>/comment_edit/', views.comment_edit, name='comment_edit'),

    path('<int:post_id>/like/', views.like, name='like'),
    path('<int:post_id>/like-async/', views.like_async, name='like_async'),
]

posts/models.py
from django.db import models
from django_resized import ResizedImageField
from django.conf import settings



# Create your models here.
class Post(models.Model):
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    # image = models.ImageField(upload_to='image/%Y/%m')
    image = ResizedImageField(
        size=[500, 500],
        crop=['middle', 'center'],
        upload_to='image/%Y/%m'
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # user_id = 

    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')

class Comment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = '__all__'
        exclude = ('user','like_users', )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

posts/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse

# Create your views here.
def index(request):
    posts = Post.objects.all().order_by('-id')
    comment_form = CommentForm()

    context = {
        'posts': posts,
        'comment_form' : comment_form,
    }

    return render(request, 'index.html', context)

def index2(request):
    posts = Post.objects.all().order_by('-id')
    comment_form = CommentForm()

    context = {
        'posts': posts,
        'comment_form': comment_form,
    }

    return render(request, 'index2.html', context)

def index3(request):
    posts = Post.objects.all().order_by('-id')
    comment_form = CommentForm()

    context = {
        'posts': posts,
        'comment_form': comment_form,
    }

    return render(request, 'index3.html', context)

def detail(request, post_id):
    post = Post.objects.get(id=post_id)
    comment_form = CommentForm()

    context = {
        'post': post,
        'comment_form' : comment_form,
    }

    return render(request, 'detail.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:index')
    else:
        form = PostForm()

    context = {
        'form' : form,
    }

    return render(request, 'form.html', context)

@login_required
def comment_create(request, post_id):
    comment_form = CommentForm(request.POST)

    if comment_form.is_valid():
        comment = comment_form.save(commit=False)

        # 현재 로그인 유저
        comment.user = request.user
        # post_id를 기준으로 찾은 post
        # comment.post_id = 
        post = Post.objects.get(id=post_id)
        comment.post = post

        comment.save()

        return redirect('posts:index')
    

def comment_delete(request, id, post_id):
    
    
    comment = Comment.objects.get(id=id)

    comment.delete()

    post = Post.objects.get(id=post_id)

    return redirect('posts:index')

def comment_edit(request, post_id, id):
    if request.method == 'POST':
        
        form = CommentForm(request.POST)
        if form.is_valid():

            comment = form.save(commit=False)
            comment.post_id = post_id
            comment.user = request.user
            comment.save()

        return redirect('posts:index')
    
    else:
        post_id = Post.objects.get(id=post_id)
        id = Comment.objects.get(id=id)
        form = CommentForm(id=id)

    context = {
        'form' : form,
    }

    return render(request, 'form.html', context)


# def comment_update(request, post_id, id):
#     comment = Comment.objects.get(id=id)

#     if request.method == 'POST':
#         form = CommentForm(request.POST, instance=comment)
#         if form.is_valid():
#             comment = form.save()
#             context = {
#                 'newContent': comment.content,
#                 'user': comment.user.username,
#             }
#         else:
#             context = {
#                 'message': 'fail'
#             }

#         return JsonResponse(context)
#     else:
#         form = CommentForm(instance=comment)

#     return HttpResponse(form)


@login_required
def like(request, post_id):

    # 좋아요 버튼을 누른 유저
    user = request.user
    post = Post.objects.get(id=post_id)

    # 이미 좋아요 버튼을 누른 경우
    if user in post.like_users.all():
    # if post in user.like_posts.all():
        post.like_users.remove(user)
        # user.like_posts.remove(post)

    # 좋아요 버튼을 아직 안누른 경우
    else:
        post.like_users.add(user)
       
        # user.like_posts.add(post)


    return redirect('posts:index')



def like_async(request, post_id):
    # print('hello')
    # context = {
    #     'message': post_id,
    # }

    user = request.user
    post = Post.objects.get(id=post_id)

    if user in post.like_users.all():
        post.like_users.remove(user)
        status = False
    else:
        post.like_users.add(user)
        status = True
    context = {
        'status': status,
        'count': len(post.like_users.all())
    }

    return JsonResponse(context)
    # 위와 비슷
    # return render(request, 'html', context)

posts/templates/_card.html
{% load bootstrap5 %}
<div class="card mt-5">
    <div class="card-header">
        <p>
            <img src="{{post.user.profile_image.url}}" alt="" class="rounded-circle" width="50px">
            <a href="{% url 'accounts:profile' username=post.user %}" class="text-reset text-decoration-none">{{post.user}}</a>
        </p>
    </div>
    <a href="{% url 'posts:detail' post_id=post.id %}">
        <img src="{{post.image.url}}"  alt="...">
    </a>
    <div class="card-body">
        <!-- <h5 class="card-title">Card title</h5> -->
        
        {% if post in user.like_posts.all %}
            <i class="bi bi-heart-fill heart" style="color: red" data-post-id="{{post.id}}">{{post.like_users.all|length}}</i> 
        {% else %}
            <i class="bi bi-heart heart" data-post-id="{{post.id}}">{{post.like_users.all|length}}</i> 
        {% endif %}
        명이 좋아합니다.

        <p class="card-text">{{post.content}}</p>
        <p class="card-text">{{post.create_at|timesince}}</p>
        <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
    </div>
    <div class="card-footer">
        {% if user.is_authenticated %}
        <form action="{% url 'posts:comment_create' post_id=post.id %}" method="POST" class="comment-form">
            {% csrf_token %}
            {% bootstrap_form comment_form %}
            <input type="submit" id="comment_create_btn">
        </form>
        <hr>
        {% endif %}
        <ul id="comment-list-{{post.id}}">
            {% for comment in post.comment_set.all %}
                <li>{{comment.user}} : {{comment.content}}
                    {% if comment.user == user %}
                        
                        <a href="{% url 'posts:comment_delete' post_id=post.id id=comment.id%}">
                            <i class="bi bi-trash trash" style="color: black" data-comment-id="{{comment.id}}" data-post-id="{{post.id}}"></i>
                        </a>
                        
                    {% endif %}
                    
                </li>
            {%endfor%}
        </ul>
            
        
    </div>
  </div>

posts/templates/detail.html
{% extends 'base.html'%}
{% load bootstrap5 %}
{% block body %}

    <div class="card mt-4">
        <div class="card-header">
            <p>
                <img src="{{post.user.profile_image.url}}" alt="" class="rounded-circle" width="50px">
                <a href="{% url 'accounts:profile' username=post.user %}" class="text-reset text-decoration-none">{{post.user}}</a>
            </p>
        </div>
        
        <img src="{{post.image.url}}"  alt="...">
        
        <div class="card-body">
            <!-- <h5 class="card-title">Card title</h5> -->
            
            {% if post in user.like_posts.all %}
                <i class="bi bi-heart-fill heart" style="color: red" data-post-id="{{post.id}}">{{post.like_users.all|length}}</i> 
            {% else %}
                <i class="bi bi-heart heart" data-post-id="{{post.id}}">{{post.like_users.all|length}}</i> 
            {% endif %}
            명이 좋아합니다.
    
            <p class="card-text">{{post.content}}</p>
            <p class="card-text">{{post.create_at|timesince}}</p>
            <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
        </div>
        <div class="card-footer">
            {% if user.is_authenticated %}
            <form action="{% url 'posts:comment_create' post_id=post.id %}" method="POST" class="comment-form">
                {% csrf_token %}
                {% bootstrap_form comment_form %}
                <input type="submit" id="comment_create_btn">
            </form>
            <hr>
            {% endif %}
            <ul id="comment-list-{{post.id}}">
                {% for comment in post.comment_set.all %}
                    <li>{{comment.user}} : {{comment.content}}
                        {% if comment.user == user %}
                            <a href="{% url 'posts:comment_edit' post_id=post.id id=comment.id%}">
                                <i class="bi bi-pen pen" style="color: black" data-comment-id="{{comment.id}}" data-post-id="{{post.id}}"></i>
                            </a>
                            <a href="{% url 'posts:comment_delete' post_id=post.id id=comment.id%}">
                                <i class="bi bi-trash trash" style="color: black" data-comment-id="{{comment.id}}" data-post-id="{{post.id}}"></i>
                            </a>
                        {% endif %}
                        
                    </li>
                {%endfor%}
            </ul>
                
            
        </div>
      </div>

{%endblock%}

posts/templates/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{%block body%}

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit">
    </form>
{%endblock%}

posts/templates/index.html
{% extends 'base.html' %}

{%block body%}
    <div class="container">
            
                
        <div class="text-xxl-end text-end">
            <span class="border border-5">
                <a href="{% url 'posts:index' %}">
                    <i class="bi bi-postage" style="color: black; height: 50px;;" ></i>
                </a>
            </span>
            <span class="border border-5">
                <a href="{% url 'posts:index2' %}">
                    <i class="bi bi-border-all" style="color: black; margin-left: 10;"></i>
                </a>
            </span>
        </div>
    </div>
    {% for post in posts %}
        {% include '_card.html' %}

    {%endfor%}

    

<!-- 좋아요 버튼 -->
    <script>
        const likeButtons = document.querySelectorAll('i.heart')
        // console.log(likeButtons)

        likeButtons.forEach((likeButton)=>{
            // console.log(likeButton)
            likeButton.addEventListener('click', (event)=>{
                let postId = event.target.dataset.postId
                console.log(postId)

                likeRequest(event.target, postId)
            })
        })

        let likeRequest = async (button, postId) => {
            // console.log(button, postId)
            // django 서버에 요청을 보낸다
            let likeURL = `/posts/${postId}/like-async/`
            let response = await fetch(likeURL)
            let result = await response.json()

            // console.log(result)
            // django 서버의 응답에 따라 좋아요 버튼을 수정한다.
            if (result.status) {
                // true => 좋아요가 눌린 경우
                button.classList.remove('bi-heart')
                button.classList.add('bi-heart-fill')
                button.style.color = 'red'
                button.innerHTML = result.count
            } else {
                // false => 좋아요 취소
                button.classList.remove('bi-heart-fill')
                button.classList.add('bi-heart')
                button.style.color = 'black'
                button.innerHTML = result.count
            }

        }
    </script>

<!-- 코멘트 수정 -->

    <script>
        // const editButtons = document.querySelectorAll('i.pen')
        // // console.log(editButtons)

        // editButtons.forEach((editButton) => {
        //     // console.log(editButton)
        //     editButton.addEventListener('click', (event)=>{
        //         console.log(event)
        //         let commentId = event.target.dataset.commentId
        //         // console.log(commentId)
        //         let postId = event.target.dataset.postId

        //         // editRequest(event.target, postId)
                
        //     })
        // })

        // let editRequest = async (button, commentId) => {
        //     let editURL = `/posts/${postId}/comments/${commentId}/comment_edit/`
        //     let response = await fetch(editURL)
        //     let result = await response.json()

        //     // console.log(result)
        // }

    </script>

    <!-- 코멘트 입력 -->
    <script>

    //     const commentForms = document.querySelectorAll('.comment-form')
    //     commentForms.forEach(function(form){
    //         form.addEventListener('submit', function(event){
    //         event.preventDefault()
            
    //         const data = new FormData(event.target)

    //         axios.post(event.target.action, data)
    //             .then(function(response){
    //                 const comment = response.data
    //                 const commentList = document.querySelector(
    //                     `#comment-list-${comment.postId}`)
    //                 const newComment = `<li>
    //                     ${comment.user} : ${comment.content}
    //                     <a href="/posts/${comment.postId}/comments/${comment.id}/update/">
    //                         <i class="bi bi-pen pen" style="color: black" data-comment-id="{{comment.id}}" data-post-id="{{post.id}}"></i>
    //                     </a>
    //                     <a href="/posts/${comment.postId}/comments/${comment.id}/delete/">
    //                         <i class="bi bi-trash trash" style="color: black" data-comment-id="{{comment.id}}" data-post-id="{{post.id}}"></i>
    //                     </a>
    //                 </li>`
    //                 commentList.insertAdjacentHTML('beforeEnd', newComment)
    //                 event.target.reset()
    //         })
    //     })
    // })
    </script> 

<!-- 코멘트 수정2 -->
<script>
    // 데이터 전송 객체 생성!
//     let comment = {
//   // 이벤트 등록
//         init: function() {
//             let _this = this;
//     // 생성 버튼 변수화
//             const createBtn = document.querySelectorAll('comment_create_btn');
//     // 생성 버튼 클릭 시, 수행할 메소드 연결!
//             createBtn.addEventListener('click', function(){
//                 _this.create();
//             });
//     // 수정 버튼 변수화
//             const updateBtns = document.querySelectorAll('i.pen');
//     // 모든 수정 버튼별, 이벤트 등록
//             updateBtns.forEach(function(item) {
//             item.addEventListener('click', function() { // 클릭 이벤트 발생시,
//                 var form = this.closest('form'); // 클릭 이벤트가 발생한 버튼에 제일 가까운 폼을 찾고,
//                 _this.update(form); // 해당 폼으로, 업데이트 수행한다!
//             });
//             });
//         },
//   // 댓글 등록
//   create: function() {
//     // 데이터
//     var data = {
//       author: document.querySelector('#comment-author').value,
//       content: document.querySelector('#comment-content').value,
//     };
//     // url에서 article의 id를 추출!
//     var split = location.pathname.split('/');
//     var articleId = split[split.length - 1];
//     // Ajax 통신
//     // - https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
//     // - https://t.ly/Vrrz
//     fetch('/api/comments/' + articleId, { // 요청을 보냄
//       method: 'POST',
//       body: JSON.stringify(data),
//       headers: {
//         'Content-Type': 'application/json'
//       }
//     }).then(function(response) { // 응답 처리
//       if (response.ok) { // 성공
//         alert('댓글이 등록되었습니다.');
//         window.location.reload(`/articles/${articleId}#comment`);
//       } else { // 실패
//         alert('댓글 등록 실패..!');
//       }
//     });
//   },
//   // 댓글 수정
//   update: function(form) {
//     // 데이터
//     var data = {
//       id: form.querySelector('#comment-id').value,
//       author: form.querySelector('#comment-author').value,
//       content: form.querySelector('#comment-content').value,
//     };
//     // url에서 article의 id를 추출!
//     var split = location.pathname.split('/');
//     var articleId = split[split.length - 1];
//     // 비동기 통신
//     fetch('/api/comments/' + data.id, { // 요청을 보냄
//       method: 'PUT',
//       body: JSON.stringify(data),
//       headers: {
//         'Content-Type': 'application/json'
//       }
//     }).then(function(response) { // 응답 처리
//       if (response.ok) { // 성공
//         alert('댓글이 수정되었습니다.');
//       } else { // 실패
//         alert('댓글 수정 실패..!');
//       }
//       window.location.reload(true); // 페이지 리로드
//     });
//   }
// };
// // 객체 초기화!
// comment.init();

</script>
    <div class="moveTopBtn" style="position: fixed;
    bottom: 1rem;
    right: 1rem;
    width: 2rem;
    height: 2rem;
    
    color: black;
    
   "><i class="bi bi-arrow-up-circle-fill align-items-center" style="width: 4rem; height: 4rem;"></i></div>

    <script>
   const topBtn = document.querySelector(".moveTopBtn");

   // 버튼 클릭 시 맨 위로 이동
   topBtn.onclick = () => {
     window.scrollTo({ top: 0, behavior: "smooth" });  
   }
    </script>

{% endblock%}

posts/templates/index2.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{%block body%}

    <div class="container">
        
            
        <div class="text-xxl-end text-end">
            <span class="border border-5">
                <a href="{% url 'posts:index' %}">
                    <i class="bi bi-postage" style="color: black; height: 50px;;" ></i>
                </a>
            </span>
            <span class="border border-5">
                <a href="{% url 'posts:index2' %}">
                    <i class="bi bi-border-all" style="color: black; margin-left: 10;"></i>
                </a>
            </span>
        </div>
    </div>


    
    <div class="row row-cols-5">
        {% for post in posts %}
            <a href="{% url 'posts:detail' post_id=post.id %}"> 
                <div class="card">
                    <img src="{{post.image.url}}" alt="">
                </div>
            </a>
        {%endfor%}
    </div>
    <div class="moveTopBtn" style="position: fixed;
    bottom: 1rem;
    right: 1rem;
    width: 2rem;
    height: 2rem;
    
    color: black;
    
   ">
   <i class="bi bi-arrow-up-circle-fill align-items-center"></i></div>

    <script>
   const topBtn = document.querySelector(".moveTopBtn");

   // 버튼 클릭 시 맨 위로 이동
   topBtn.onclick = () => {
     window.scrollTo({ top: 0, behavior: "smooth" });  
   }
    </script>

{%endblock%}

posts/templates/updateForm.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{%block body%}

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit"> <input type="reset">
    </form>
{%endblock%}