INSTA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/follow/', views.follow, name='follow'),
    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_resized import ResizedImageField

# Create your models here.
class User(AbstractUser):
    profile_image = ResizedImageField(
        size=[500, 500],
        crop=['middle', 'center'],
        upload_to='profile',
    )
    # post_set =
    # comment_set = 
    # like_posts =

    followings = models.ManyToManyField('self', related_name='followers', symmetrical=False)
    # user_set => followers

posts/models.py
from django.db import models
from django_resized import ResizedImageField
from django.conf import settings



# Create your models here.
class Post(models.Model):
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    # image = models.ImageField(upload_to='image/%Y/%m')
    image = ResizedImageField(
        size=[500, 500],
        crop=['middle', 'center'],
        upload_to='image/%Y/%m'
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # user_id = 

    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')

class Comment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        # model = User
        fields = ('username', 'profile_image', )

class CustomAuthenticationForm(AuthenticationForm):
    pass

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from posts.models import Post

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
    else:
        form = CustomUserCreationForm()

    context = {
        'form': form,
    }

    return render(request, 'accounts/form.html', context)

def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('posts:index')

    else:
        form = CustomAuthenticationForm()

    context = {
        'form': form,
    }

    return render(request, 'accounts/form.html', context)

def profile(request, username):
    User = get_user_model()

    user_info = User.objects.get(username=username)

    context = {
        'user_info': user_info,
    }

    return render(request, 'accounts/profile.html', context)

@login_required
def follow(request, username):
    User = get_user_model()
    
    me = request.user
    you = User.objects.get(username=username)

    # 팔로잉이 이미 되어있는 경우
    # if me in you.followers.all():
    if you in me.followings.all():
        me.followings.remove(you)

    # 팔로잉이 아직 안 된 경우
    else:
        me.followings.add(you)

    return redirect('accounts:profile', username=username)


@login_required
def logout(request):
    # post = Post.objects.all(id=post_id)
    auth_logout(request)
    return redirect('posts:index')

accounts/templates/accounts/form.html
{%extends 'base.html' %}
{% load bootstrap5 %}

{%block body%}
<h1>sign up</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form%}
    <input type="submit">
</form>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{%block body%}

<div class="row">
    <div class="col-4">
        <img src="{{user_info.profile_image.url}}" alt="" class="img-fluid rounded-circle">
    </div>
    <div class="col-8">
        <div class="row">
            <div class="col-3">{{user_info.username}}</div>

            <!-- user: 로그인한 사람 / user_info: 프로필 페이지의 유저 -->
            {% if user != user_info %}
            <div class="col-4">
                {% if user in user_info.followers.all %}
                    <a href="{% url 'accounts:follow' username=user_info.username %}" class="btn btn-primary btn-sm">팔로잉</a>
                {% else %}
                    <a href="{% url 'accounts:follow' username=user_info.username %}" class="btn btn-secondary btn-sm">팔로우</a>
                {% endif %}
            </div>
            {% endif %}
        </div>
        <div class="row">
        <div class="col">게시물 {{user_info.post_set.all|length}}</div>
        <div class="col">팔로워 {{user_info.followers.all|length}}</div>
        <div class="col">팔로우 {{user_info.followings.all|length}}</div>
        </div>
    </div>
</div>

<div class="row row-cols-3">
    {% for post in user_info.post_set.all %}
        <div class="col">
            <div class="card">
                <img src="{{post.image.url}}" alt="">
            </div>
        </div>
    {%endfor%}
</div>


{%endblock%}